//
//  MoshBase64Key.swift
//  rootshell
//
//  Mosh session key parsing and validation
//

import Foundation

/// Represents a mosh session key (22 characters base64)
/// The key is generated by mosh-server and transmitted via SSH
/// Format: "MOSH CONNECT <port> <22-char-base64-key>"
struct MoshBase64Key: Equatable, Sendable {
    /// The raw 16-byte (128-bit) key data
    let keyData: Data

    /// The original base64 string (22 characters)
    let base64String: String

    // MARK: - Initialization

    /// Creates a key from a 22-character base64 string
    /// - Parameter base64String: The 22-character base64-encoded key from mosh-server
    /// - Throws: MoshError.invalidSessionKey if parsing fails
    init(base64String: String) throws {
        // Mosh uses 22-character base64 which encodes to 16 bytes (128 bits)
        // Standard base64: 16 bytes -> 22 chars (with 2 padding chars = 24, but mosh omits padding)
        guard base64String.count == 22 else {
            throw MoshError.invalidSessionKey(
                reason: "Expected 22 characters, got \(base64String.count)"
            )
        }

        // Validate characters are valid base64
        let base64Chars = CharacterSet(charactersIn: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")
        guard base64String.unicodeScalars.allSatisfy({ base64Chars.contains($0) }) else {
            throw MoshError.invalidSessionKey(
                reason: "Invalid base64 characters in key"
            )
        }

        // Add padding for standard base64 decoding (22 chars needs 2 padding)
        let paddedBase64 = base64String + "=="

        guard let data = Data(base64Encoded: paddedBase64) else {
            throw MoshError.invalidSessionKey(
                reason: "Failed to decode base64 key"
            )
        }

        guard data.count == 16 else {
            throw MoshError.invalidSessionKey(
                reason: "Key must be 16 bytes (128 bits), got \(data.count) bytes"
            )
        }

        self.keyData = data
        self.base64String = base64String
    }

    /// Creates a key from raw 16-byte data
    /// - Parameter keyData: The raw 16-byte key
    /// - Throws: MoshError.invalidSessionKey if data is not 16 bytes
    init(keyData: Data) throws {
        guard keyData.count == 16 else {
            throw MoshError.invalidSessionKey(
                reason: "Key must be 16 bytes (128 bits), got \(keyData.count) bytes"
            )
        }

        self.keyData = keyData

        // Convert to 22-character base64 (remove padding)
        let base64 = keyData.base64EncodedString()
        self.base64String = String(base64.dropLast(2))  // Remove "==" padding
    }

    // MARK: - Key Bytes

    /// Returns the key as a byte array (for crypto operations)
    nonisolated var bytes: [UInt8] {
        Array(keyData)
    }

    // MARK: - Parsing

    /// Parses a mosh-server connection response
    /// Format: "MOSH CONNECT <port> <key>"
    /// - Parameter response: The stdout from mosh-server
    /// - Returns: Tuple of (port, key) if successful
    /// - Throws: MoshError.invalidServerResponse if parsing fails
    static func parseServerResponse(_ response: String) throws -> (port: Int, key: MoshBase64Key) {
        // Look for the MOSH CONNECT line
        // Example: "MOSH CONNECT 60001 abcdefghijklmnopqrstuv"
        let lines = response.components(separatedBy: .newlines)

        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.hasPrefix("MOSH CONNECT ") {
                let parts = trimmed.components(separatedBy: " ")
                guard parts.count >= 4 else {
                    throw MoshError.invalidServerResponse(received: trimmed)
                }

                guard let port = Int(parts[2]) else {
                    throw MoshError.invalidServerResponse(
                        received: "Invalid port: \(parts[2])"
                    )
                }

                let keyString = parts[3]
                let key = try MoshBase64Key(base64String: keyString)

                return (port: port, key: key)
            }
        }

        throw MoshError.invalidServerResponse(
            received: "No MOSH CONNECT line found in response"
        )
    }
}

// MARK: - CustomStringConvertible

extension MoshBase64Key: CustomStringConvertible {
    var description: String {
        // Show only first 4 characters for security
        let prefix = String(base64String.prefix(4))
        return "MoshKey(\(prefix)...)"
    }
}
